# Generated by Django 5.0.6 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_liked', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to='website/images')),
            ],
        ),
    ]
